import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { SITE_URL } from "@/lib/site";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Reserved for the hero statement only, so it stays distinctive.
const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

const DESCRIPTION =
  "MS Computer Science at UIC, Applied AI/ML. Building intelligent systems and agentic workflows.";

// Share images come from app/opengraph-image.png and app/twitter-image.png
// (generated by scripts/og-image.tsx); Next adds those tags itself.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: "Vaishnavi Jadhav", template: "%s | Vaishnavi Jadhav" },
  description: DESCRIPTION,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: "Vaishnavi Jadhav",
    title: "Vaishnavi Jadhav",
    description: DESCRIPTION,
    url: "/",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Vaishnavi Jadhav",
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
